export const carMarks = ['Acura CL', 'Acura MDX', 'Acura NSX', 'Acura RDX', 'Acura RL', 'Alfa Romeo 155', 'Alfa Romeo 156', 'Alfa Romeo 159',
'Alfa Romeo 164', 'Alfa Romeo 166', 'Alfa Romeo 1900', 'Alfa Romeo 2600', 'Aston Martin DB7', 'Aston Martin DB9', 'Land Rover Discovery',
'Aston Martin DBS', 'Aston Martin DBX', 'Aston Martin Lagonda', 'Audi 100', 'Audi 200', 'Audi 50', 'Audi 80', 'Land Rover Freelander',
'Audi 90', 'Audi 920', 'Audi A1', 'Audi A2', 'Audi A3', 'Audi A4', 'Audi A5', 'Audi A6', 'Audi A7', 'Audi A8', 'ИЖ 2126 «Ода»',  'BMW 321',
'Bentley Azure', 'Bentley Bentayga', 'Bentley Brooklands', 'Bentley Continental', 'Bentley Continental Flying Spur',  'Lifan Myway',
'Bentley Continental GT', 'Bentley Eight', 'Bentley Flying Spur', 'Bentley Mark VI', 'Bentley Mulsanne', 'Bentley R Type', 'Honda Acty',
'Bentley S', 'Bentley T-Series','Bentley Turbo R', 'BMW 3 серии', 'BMW 3/15', 'BMW 315', 'BMW 3200',  'Lamborghini Veneno', 'Lancia Hyena',
'BMW 326', 'BMW 327', 'BMW 340', 'BMW 4 серии', 'BMW 5 серии', 'BMW 501', 'BMW 502', 'BMW 503', 'BMW 507', 'BMW 6 серии', 'Dodge 600',
'Bugatti Chiron', 'Bugatti EB 110', 'Bugatti EB 112', 'Bugatti EB Veyron 16.4', 'Bugatti Type 55 ', 'Cadillac ATS', 'УАЗ Patriot',
'Cadillac ATS-V', 'Cadillac BLS', 'Cadillac Brougham', 'Cadillac Catera', 'Cadillac CT4', 'Cadillac CT5','Cadillac CT6', 'Москвич 427',
'Chery Amulet (A15)', 'Chery Arrizo 3', 'Chery Arrizo 6', 'Chery Arrizo 7', 'Chevrolet Starcraft', 'Chevrolet Suburban', 'УАЗ Hunter',
'Chevrolet Tacuma', 'Chevrolet Tahoe', 'Chevrolet Tavera', 'Chevrolet Tracker', 'Chevrolet TrailBlazer', 'Chevrolet Trans Sport',
'Chevrolet Traverse', 'Chevrolet Trax', 'Chevrolet Uplander', 'Chevrolet Van', 'Chevrolet Vectra', 'Chevrolet Venture', 'Peugeot 306',
'Chevrolet Viva', 'Chevrolet Volt', 'Chevrolet Zafira','Chrysler 180', 'Chrysler 200', 'Chrysler 300', 'Chrysler 300C', 'Kia Cerato',
'Chrysler 300M', 'Citroen C2', 'Citroen C3', 'Citroen C4', 'Citroen C5', 'Citroen C6', 'Citroen C8', 'Citroen CX', 'Citroen DS',
'Citroen Dyane', 'Citroen E-Mehari', 'Citroen Evasion', 'Citroen GS', 'Citroen Jumpy', 'Citroen LN', 'Citroen Nemo', 'Citroen Saxo',
'Citroen SM', 'Citroen SpaceTourer', 'Citroen Traction Avant', 'Citroen Visa', 'Citroen Xantia', 'Citroen XM', 'Citroen Xsara',
'Daewoo LeMans', 'Daewoo Magnus', 'Daewoo Matiz', 'Daewoo Musso', 'Daewoo Nexia', 'Daewoo Nubira', 'Daewoo Prince', 'Daewoo Racer',
'Daewoo Rezzo', 'Daewoo Royale', 'Daewoo Sens', 'Daewoo Tacuma', 'Daewoo Tico', 'Daewoo Tosca', 'Daewoo Winstorm', 'ЗАЗ 1105 «Дана»',
'Dodge Aries', 'Dodge Avenger', 'Dodge Caliber', 'Dodge Caravan', 'Dodge Challenger', 'Dodge Charger', 'Dodge Colt', 'Dodge Custom Royal',
'Dodge D8', 'Dodge Dakota', 'Dodge Dart', 'Dodge Daytona', 'Dodge Diplomat', 'Dodge Durango', 'Dodge Dynasty', 'Dodge Intrepid',
'Dodge Journey', 'Ferrari 296', 'Ferrari 328', 'Ferrari 348', 'Ferrari 360', 'Ferrari 400', 'Ferrari 412', 'Ferrari 456', 'Ferrari 458',
'Ferrari 488', 'Ferrari 550', 'Ferrari 599', 'Ferrari 612', 'Ferrari 812', 'Fiat Palio', 'Fiat Panda', 'Fiat Punto', 'Fiat Qubo',
'Fiat Regata', 'Ford Aspire', 'Ford Bronco', 'Ford Capri', 'Ford Consul', 'Ford Contour', 'Geely Atlas', 'Geely Coolray', 'Lifan Solano',
'Geely Emgrand 7', 'Geely GC6', 'Geely GC9', 'Haval H2', 'Haval H5', 'Haval H6', 'Haval H8', 'Haval H9', 'Honda Beat',  'Mazda 6',
'Honda Civic', 'Honda Edix', 'Hyundai Creta', 'Hyundai Encino', 'Hyundai Entourage', 'Hyundai Grace', 'Hyundai Grand Starex', 'Opel Vectra',
'Infiniti G', 'Infiniti I', 'Infiniti J', 'Infiniti M', 'Infiniti Q', 'Jaguar E-type', 'Jaguar F-Type', 'Mazda Capella', 'Subaru Leone',
'Kia Elan', 'Kia Rio', 'Kia Sportage', 'LADA (ВАЗ) Granta', 'LADA (ВАЗ) Kalina', 'LADA (ВАЗ) Largus', 'LADA (ВАЗ) Niva', 'Москвич 426',
'Lamborghini Silhouette', 'Lamborghini Sián', 'Lamborghini Urraco', 'Lamborghini Urus', 'Maserati Kyalami', 'Maserati Levante', 'Saab 99',
'Lancia Kappa', 'Lancia Lambda', 'Lancia Lybra', 'Land Rover Defender', 'Lexus GS', 'Lexus GX', 'Lexus HS', 'Lifan Smily', 'Москвич 430',
'Land Rover Range Rover', 'Lexus CT', 'Lexus ES', 'УАЗ Pickup', 'УАЗ Астеро', 'Ё-мобиль Ё-Кроссовер', 'ЗАЗ 1103 «Славута»', 'ЗИЛ 111',
'Lincoln MKC', 'Lincoln MKS', 'Lincoln MKT', 'Maserati Khamsin', 'ЗИЛ 114', 'ЗИЛ 117', 'ИЖ 2125 «Комби»', 'ЗАЗ 1102 «Таврия»', 'Volvo 850',
'Mazda CX-3', 'Mazda Etude', 'McLaren 540C', 'McLaren 570S', 'McLaren 650S', 'Mercedes-Benz A-Класс', 'Mercedes-Benz B-Класс', 'Saab 96',
'Mercedes-Benz C-Класс', 'Mercedes-Benz CLK-Класс', 'MINI Coupe', 'MINI Hatch', 'MINI Paceman', 'Mitsubishi Chariot', 'ГАЗ 13 «Чайка»',
'Mitsubishi Colt', 'Mitsubishi Cordia', 'Mitsubishi Debonair', 'Nissan Bassara', 'Nissan Bluebird', 'Nissan Cedric', 'Volkswagen Lupo',
'Nissan Cherry', 'Oldsmobile Achieva', 'Oldsmobile Cutlass', 'Oldsmobile Firenza', 'Oldsmobile Intrigue', 'Opel Astra', 'Pontiac G6',
'Opel Corsa', 'Opel Insignia', 'Opel Omega', 'Peugeot 206', 'Peugeot 207', 'Peugeot 308', 'Peugeot 402', 'Tesla Model S', 'ГАЗ 21 «Волга»',
'Peugeot 403', 'Peugeot 404', 'Pontiac G4', 'Pontiac G5', 'Pontiac G8', 'Porsche 356', 'Porsche 911', 'Porsche 912', 'ГАЗ 2330 «Тигр»',
'Porsche 914', 'Porsche Cayenne', 'Porsche Cayman', 'Renault Duster', 'Renault Espace', 'Renault Floride', 'Renault Fuego', 'Volvo 940',
'Renault Kaptur', 'Renault Koleos', 'Rolls-Royce Camargue', 'Rolls-Royce Corniche', 'Rolls-Royce Cullinan', 'Saab 93', 'Saab 95', 
 'Skoda Citigo', 'Skoda Enyaq', 'Skoda Fabia', 'Skoda Favorit', 'Subaru Domingo', 'ГАЗ 2308 «Атаман»', 'Volkswagen Tiguan', 'Volvo 440',
'Subaru Pleo', 'Subaru Sambar', 'Suzuki Across', 'Suzuki Cappuccino', 'Suzuki Carry', 'Tesla Model 3', 'Volvo 740', 'Volkswagen Polo',
'Tesla Model X', 'Tesla Model Y', 'Toyota Auris', 'Toyota Camry', 'Toyota Comfort', 'Volkswagen Golf'];